#! /bin/sh

###############################################
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗#
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║#
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║#
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║#
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║#
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝#
###############################################

# Autostart

pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar


# Monitor setup

bspc monitor DVI-I-1 -d desktop web multimedia music chat games
bspc monitor HDMI-0 -d obs other


# Bspwm Settings

bspc config border_width         2
bspc config window_gap          19

bspc config auto_alternate true
bspc config auto_cancel true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config apply_floating_atom    true

# Apps to workspace

bspc rule -a "Gimp-2.10" desktop=multimedia
bspc rule -a Google-chrome desktop=web follow=on
bspc rule -a "firefox" desktop=web follow=no
bspc rule -a KotatogramDesktop desktop=chat
bspc rule -a Smplayer desktop=multimedia
bspc rule -a mpv desktop=multimedia
bspc rule -a obs desktop=obs
bspc rule -a discord desktop=obs
bspc rule -a "Deluge-gtk" desktop=multimedia

# Window Rules

bspc rule -a Lutris desktop=games state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a "Pamac-manager" state=floating
bspc rule -a Galculator state=floating
bspc rule -a Etcher state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a "Execute File" state=floating
bspc rule -a Wpg state=floating
bspc rule -a Origin state=floating
bspc rule -a Yad state=floating
bspc rule -a Steam state=floating desktop=games follow=on
bspc rule -a Baobab state=floating

# Fullscreen
bspc rule -a "browser-window" state=fullscreen

# External Rules

bspc config external_rules_command $HOME/.scripts/windows.sh

#wpgtk
bash $HOME/.config/bspwm/bspwm_colors.sh &
bash $HOME/.config/wpg/wp_init.sh &

#Polybar

$HOME/.config/polybar/bspwm.sh &
