#! /bin/sh

###############################################
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗#
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║#
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║#
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║#
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║#
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝#
###############################################

# Autostart

sxhkd &

killall dunst && dunst -config ~/.cache/wal/dunstrcbspwm &

# Polybar

$HOME/.config/polybar/bspwm/bspwm.sh
#$HOME/.config/polybar/bspwm2/bspwm.sh
#$HOME/.config/polybar/bspwm3/bspwm.sh

# Monitor setup

bspc monitor DP-2 -d desktop web multimedia music chat games
bspc monitor DVI-I-1 -d obs other

# Bspwm Settings

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config initial_polarity second_child

bspc config focus_follows_pointer true

# Pywal Colors

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

# Apps to workspace

bspc rule -a "Gimp-2.10" desktop=multimedia
bspc rule -a "Vivaldi-stable" desktop=web
bspc rule -a TelegramDesktop desktop=chat
bspc rule -a Smplayer desktop=multimedia
bspc rule -a mpv desktop=multimedia
bspc rule -a obs desktop=obs
bspc rule -a Vmware desktop=multimedia
bspc rule -a Steam desktop=games
bspc rule -a discord desktop=chat
bspc rule -a VK desktop=chat
bspc rule -a REAPER desktop=multimedia

# Floating Apps

bspc rule -a Lutris desktop=games state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a "Pamac-manager" state=floating
bspc rule -a Galculator state=floating
bspc rule -a Gnac state=floating
bspc rule -a Etcher state=floating
bspc rule -a Woeusbgui state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a File-roller state=floating
bspc rule -a XTerm state=floating
bspc rule -a Yad state=floating

# External Rules

bspc config external_rules_command $HOME/.scripts/windows.sh
