#!/usr/bin/env bash
pkg_updates() {
	updates=$(dnf updateinfo list | wc -l)
  if [ $updates == 0 ]; then
    echo "^c#94af7d^ Fully Updated"
  else
    echo "^c#94af7d^ $updates"" updates"
  fi
}
echo "^c#94af7d^  $(pkg_updates)"
